name: MLHyperparameterTuning
channels:
  - conda-forge
dependencies:
  - python=3.6
  - nb_conda_kernels==2.2.1
  - pandas==0.23.4
  - scikit-learn==0.20.0
  - lightgbm==2.2.1
  - pip:
    - prompt_toolkit==2.0.9
    - azure-cli==2.0.69
    - azureml-sdk[notebooks]==1.0.48
    - papermill==0.14.2
